// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Empleado;
import java.util.Date;

privileged aspect Empleado_Roo_JavaBean {
    
    public Date Empleado.getInicio() {
        return this.inicio;
    }
    
    public void Empleado.setInicio(Date inicio) {
        this.inicio = inicio;
    }
    
}
