// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Puesto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Puesto_Roo_Configurable {
    
    declare @type: Puesto: @Configurable;
    
}
