// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Puesto;

privileged aspect Puesto_Roo_JavaBean {
    
    public String Puesto.getNombre() {
        return this.nombre;
    }
    
    public void Puesto.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
