// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.UsuarioEmpresa;
import javax.persistence.Entity;

privileged aspect UsuarioEmpresa_Roo_Jpa_Entity {
    
    declare @type: UsuarioEmpresa: @Entity;
    
}
