// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Admin;
import es.uca.iw.tempojobs.domain.AdminDataOnDemand;
import es.uca.iw.tempojobs.domain.AdminIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdminIntegrationTest: @Transactional;
    
    @Autowired
    AdminDataOnDemand AdminIntegrationTest.dod;
    
    @Test
    public void AdminIntegrationTest.testCountAdmins() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = Admin.countAdmins();
        Assert.assertTrue("Counter for 'Admin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdmin() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = Admin.findAdmin(id);
        Assert.assertNotNull("Find method for 'Admin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Admin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testFindAllAdmins() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = Admin.countAdmins();
        Assert.assertTrue("Too expensive to perform a find all test for 'Admin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Admin> result = Admin.findAllAdmins();
        Assert.assertNotNull("Find all method for 'Admin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Admin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdminEntries() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = Admin.countAdmins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Admin> result = Admin.findAdminEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Admin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Admin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminIntegrationTest.testFlush() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = Admin.findAdmin(id);
        Assert.assertNotNull("Find method for 'Admin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdmin(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Admin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminIntegrationTest.testMergeUpdate() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = Admin.findAdmin(id);
        boolean modified =  dod.modifyAdmin(obj);
        Integer currentVersion = obj.getVersion();
        Admin merged = (Admin)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Admin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        Admin obj = dod.getNewTransientAdmin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Admin' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Admin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testRemove() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = Admin.findAdmin(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Admin' with identifier '" + id + "'", Admin.findAdmin(id));
    }
    
}
