// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Estado;
import es.uca.iw.tempojobs.domain.EstadoDataOnDemand;
import es.uca.iw.tempojobs.domain.EstadoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstadoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstadoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstadoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EstadoIntegrationTest: @Transactional;
    
    @Autowired
    EstadoDataOnDemand EstadoIntegrationTest.dod;
    
    @Test
    public void EstadoIntegrationTest.testCountEstadoes() {
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", dod.getRandomEstado());
        long count = Estado.countEstadoes();
        Assert.assertTrue("Counter for 'Estado' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstadoIntegrationTest.testFindEstado() {
        Estado obj = dod.getRandomEstado();
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estado' failed to provide an identifier", id);
        obj = Estado.findEstado(id);
        Assert.assertNotNull("Find method for 'Estado' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Estado' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EstadoIntegrationTest.testFindAllEstadoes() {
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", dod.getRandomEstado());
        long count = Estado.countEstadoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Estado', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Estado> result = Estado.findAllEstadoes();
        Assert.assertNotNull("Find all method for 'Estado' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Estado' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstadoIntegrationTest.testFindEstadoEntries() {
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", dod.getRandomEstado());
        long count = Estado.countEstadoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Estado> result = Estado.findEstadoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Estado' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Estado' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstadoIntegrationTest.testFlush() {
        Estado obj = dod.getRandomEstado();
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estado' failed to provide an identifier", id);
        obj = Estado.findEstado(id);
        Assert.assertNotNull("Find method for 'Estado' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstado(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Estado' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstadoIntegrationTest.testMergeUpdate() {
        Estado obj = dod.getRandomEstado();
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estado' failed to provide an identifier", id);
        obj = Estado.findEstado(id);
        boolean modified =  dod.modifyEstado(obj);
        Integer currentVersion = obj.getVersion();
        Estado merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Estado' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstadoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", dod.getRandomEstado());
        Estado obj = dod.getNewTransientEstado(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Estado' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Estado' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Estado' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EstadoIntegrationTest.testRemove() {
        Estado obj = dod.getRandomEstado();
        Assert.assertNotNull("Data on demand for 'Estado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estado' failed to provide an identifier", id);
        obj = Estado.findEstado(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Estado' with identifier '" + id + "'", Estado.findEstado(id));
    }
    
}
