// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Experiencia;
import es.uca.iw.tempojobs.domain.ExperienciaDataOnDemand;
import es.uca.iw.tempojobs.domain.ExperienciaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExperienciaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExperienciaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExperienciaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExperienciaIntegrationTest: @Transactional;
    
    @Autowired
    ExperienciaDataOnDemand ExperienciaIntegrationTest.dod;
    
    @Test
    public void ExperienciaIntegrationTest.testCountExperiencias() {
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", dod.getRandomExperiencia());
        long count = Experiencia.countExperiencias();
        Assert.assertTrue("Counter for 'Experiencia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExperienciaIntegrationTest.testFindExperiencia() {
        Experiencia obj = dod.getRandomExperiencia();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to provide an identifier", id);
        obj = Experiencia.findExperiencia(id);
        Assert.assertNotNull("Find method for 'Experiencia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Experiencia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExperienciaIntegrationTest.testFindAllExperiencias() {
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", dod.getRandomExperiencia());
        long count = Experiencia.countExperiencias();
        Assert.assertTrue("Too expensive to perform a find all test for 'Experiencia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Experiencia> result = Experiencia.findAllExperiencias();
        Assert.assertNotNull("Find all method for 'Experiencia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Experiencia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExperienciaIntegrationTest.testFindExperienciaEntries() {
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", dod.getRandomExperiencia());
        long count = Experiencia.countExperiencias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Experiencia> result = Experiencia.findExperienciaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Experiencia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Experiencia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExperienciaIntegrationTest.testFlush() {
        Experiencia obj = dod.getRandomExperiencia();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to provide an identifier", id);
        obj = Experiencia.findExperiencia(id);
        Assert.assertNotNull("Find method for 'Experiencia' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExperiencia(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Experiencia' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExperienciaIntegrationTest.testMergeUpdate() {
        Experiencia obj = dod.getRandomExperiencia();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to provide an identifier", id);
        obj = Experiencia.findExperiencia(id);
        boolean modified =  dod.modifyExperiencia(obj);
        Integer currentVersion = obj.getVersion();
        Experiencia merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Experiencia' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExperienciaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", dod.getRandomExperiencia());
        Experiencia obj = dod.getNewTransientExperiencia(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Experiencia' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Experiencia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExperienciaIntegrationTest.testRemove() {
        Experiencia obj = dod.getRandomExperiencia();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Experiencia' failed to provide an identifier", id);
        obj = Experiencia.findExperiencia(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Experiencia' with identifier '" + id + "'", Experiencia.findExperiencia(id));
    }
    
}
