// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.Experiencia;
import es.uca.iw.tempojobs.domain.ExperienciaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ExperienciaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExperienciaDataOnDemand: @Component;
    
    private Random ExperienciaDataOnDemand.rnd = new SecureRandom();
    
    private List<Experiencia> ExperienciaDataOnDemand.data;
    
    public Experiencia ExperienciaDataOnDemand.getNewTransientExperiencia(int index) {
        Experiencia obj = new Experiencia();
        setFFechaFinal(obj, index);
        setFFechaInicio(obj, index);
        setSEmpresa(obj, index);
        setSPuesto(obj, index);
        return obj;
    }
    
    public void ExperienciaDataOnDemand.setFFechaFinal(Experiencia obj, int index) {
        Date fFechaFinal = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFFechaFinal(fFechaFinal);
    }
    
    public void ExperienciaDataOnDemand.setFFechaInicio(Experiencia obj, int index) {
        Date fFechaInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFFechaInicio(fFechaInicio);
    }
    
    public void ExperienciaDataOnDemand.setSEmpresa(Experiencia obj, int index) {
        String sEmpresa = "sEmpresa_" + index;
        if (sEmpresa.length() > 32) {
            sEmpresa = sEmpresa.substring(0, 32);
        }
        obj.setSEmpresa(sEmpresa);
    }
    
    public void ExperienciaDataOnDemand.setSPuesto(Experiencia obj, int index) {
        String sPuesto = "sPuesto_" + index;
        if (sPuesto.length() > 32) {
            sPuesto = sPuesto.substring(0, 32);
        }
        obj.setSPuesto(sPuesto);
    }
    
    public Experiencia ExperienciaDataOnDemand.getSpecificExperiencia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Experiencia obj = data.get(index);
        Long id = obj.getId();
        return Experiencia.findExperiencia(id);
    }
    
    public Experiencia ExperienciaDataOnDemand.getRandomExperiencia() {
        init();
        Experiencia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Experiencia.findExperiencia(id);
    }
    
    public boolean ExperienciaDataOnDemand.modifyExperiencia(Experiencia obj) {
        return false;
    }
    
    public void ExperienciaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Experiencia.findExperienciaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Experiencia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Experiencia>();
        for (int i = 0; i < 10; i++) {
            Experiencia obj = getNewTransientExperiencia(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
