// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.tempojobs.domain;

import es.uca.iw.tempojobs.domain.InscripcionIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InscripcionIntegrationTest_Roo_Configurable {
    
    declare @type: InscripcionIntegrationTest: @Configurable;
    
}
